services:
  vaultwarden:
    image: vaultwarden/server:1.33.1
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: https://${DOMAIN} 
      SIGNUPS_ALLOWED: "false"
    volumes:
      - ${DATA_DIR}:/data
    ports:
      - 80:80
