services:
  perverse:
    build:
      context: https://github.com/reonokiy/perverse.git
      dockerfile: Dockerfile
    container_name: perverse
    restart: unless-stopped
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      MASTODON_INSTANCE: ${MASTODON_INSTANCE}
      MASTODON_ACCESS_TOKEN: ${MASTODON_ACCESS_TOKEN}
