services:
  gotosocial:
    image: superseriousbusiness/gotosocial:0.19.1
    container_name: gotosocial
    restart: always
    environment:
      GTS_HOST: ${GTS_HOST}
      GTS_TRUSTED_PROXIES: ${GTS_TRUSTED_PROXIES}
      GTS_INSTANCE_LANGUAGE: ${GTS_INSTANCE_LANGUAGE}
      GTS_DB_TYPE: sqlite
      GTS_DB_ADDRESS: /gotosocial/storage/sqlite.db
      GTS_OIDC_ENABLED: true
      GTS_OIDC_ISSUER: ${GTS_OIDC_ISSUER}
      GTS_OIDC_IDP_NAME: ${GTS_OIDC_IDP_NAME}
      GTS_OIDC_LINK_EXISTING: ${GTS_OIDC_LINK_EXISTING:-true}
      GTS_OIDC_ALLOWED_GROUPS: ${GTS_OIDC_ALLOWED_GROUPS}
      GTS_OIDC_ADMIN_GROUPS: ${GTS_OIDC_ADMIN_GROUPS}
      GTS_OIDC_CLIENT_ID: ${GTS_OIDC_CLIENT_ID}
      GTS_OIDC_CLIENT_SECRET: ${GTS_OIDC_CLIENT_SECRET}
      GTS_STORAGE_BACKEND: s3
      GTS_STORAGE_S3_PROXY: false
      GTS_STORAGE_S3_BUCKET: ${GTS_STORAGE_S3_BUCKET}
      GTS_STORAGE_S3_ENDPOINT: ${GTS_STORAGE_S3_ENDPOINT}
      GTS_STORAGE_S3_ACCESS_KEY: ${GTS_STORAGE_S3_ACCESS_KEY}
      GTS_STORAGE_S3_SECRET_KEY: ${GTS_STORAGE_S3_SECRET_KEY}
    ports:
      - ${HTTP_PORT:-80}:8080
    volumes:
      - ${DATA_DIR:-./data}/gotosocial:/gotosocial/storage
      - ${DATA_DIR:-./data}/cache:/gotosocial/.cache

