services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR:-./data}/tsdproxy/data:/data
      - ${DATA_DIR:-./data}/tsdproxy/config:/config
    restart: always
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: nokiy
      POSTGRES_USER: nokiy
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-nokiy}
    volumes:
      - ${DATA_DIR:-./data}/postgres:/var/lib/postgresql/data
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "postgres"
