services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:${ZO_VERSION:-v0.14.7}
    container_name: openobserve
    environment:
      ZO_HTTP_PORT: 5080
      ZO_GRPC_PORT: 5081
      ZO_DATA_DIR: /data
      ZO_ROOT_USER_EMAIL: ${EMAIL}
      ZO_ROOT_USER_PASSWORD: ${PASSWORD}
      ZO_WEB_URL: https://${DOMAIN}
      ZO_TELEMETRY: false
    restart: always
    volumes:
      - ${DATA_DIR:-./data}/openobserve:/data:Z
    ports:
      - 80:5080
      - 5081:5081
  
  vector:
    image: timberio/vector:${VECTOR_VERSION:-0.46.1-debian}
    container_name: vector
    restart: always
    command: [ "--config", "/etc/vector/vector.toml" ]
    environment:
      OTLP_URI: ${OTLP_URI}
      OTLP_USER: ${OTLP_USER}
      OTLP_PASSWORD: ${OTLP_PASSWORD}
    volumes:
      - ${VECTOR_CONFIG_PATH:-./vector.toml}:/etc/vector/vector.toml:ro
      - ${DATA_DIR:-./data}/vector:/var/lib/vector:Z
      - /var/run/docker.sock:/var/run/docker.sock
    

