data_dir = "/var/lib/vector"

[api]
enabled = false

[sources.observe_nokiy_net_logs]
type = "docker_logs"
include_containers = ["openobserve"]

[sources.observe_nokiy_net_metrics]
type = "prometheus_scrape"
endpoints = ["http://openobserve:5080/metrics"]

[sinks.openobserve]
inputs = ["observe_nokiy_net_logs", "observe_nokiy_net_metrics"]
type = "http"
uri = "${OPENOBSERVE_URL}"
method = "post"
auth.strategy = "basic"
auth.user = "${OPENOBSERVE_USER}"
auth.password = "${OPENOBSERVE_PASSWORD}"
compression = "gzip"
encoding.codec = "json"
encoding.timestamp_format = "rfc3339"
healthcheck.enabled = false
