data_dir = "/var/lib/vector"

[api]
enabled = false

[sources.observe_nokiy_net_logs]
type = "docker_logs"
include_containers = ["openobserve"]

[sources.observe_nokiy_net_metrics]
type = "prometheus_scrape"
endpoints = ["http://openobserve:5080/metrics"]

[sinks.otel_logs]
type = "opentelemetry"
encoding = "json"
inputs = ["observe_nokiy_net_logs"]
protocol.type = "http"
protocol.uri = "${OTEL_URI}"
protocol.auth.strategy = "basic"
protocol.auth.user = "${OTEL_USER}"
protocol.auth.password = "${OTEL_PASSWORD}"
protocol.compression = "zstd"


# [sinks.otel_metrics]
# type = "opentelemetry"
# inputs = ["my-source-or-transform-id"]

# [sinks.otel_traces]
# type = "opentelemetry"
# inputs = ["my-source-or-transform-id"]
