data_dir = "/var/lib/vector"

[api]
enabled = false

[sources.observe_nokiy_net_logs]
type = "docker_logs"
include_containers = ["openobserve"]

[sources.observe_nokiy_net_metrics]
type = "prometheus_scrape"
endpoints = ["http://openobserve:5080/metrics"]

[sinks.observe_nokiy_net]
type = "opentelemetry"
encoding.codec = "json"
inputs = ["observe_nokiy_net_logs", "observe_nokiy_net_metrics"]
protocol.type = "http"
protocol.uri = "${OTLP_URI}/api/default"
protocol.auth.strategy = "basic"
protocol.auth.user = "${OTLP_USER}"
protocol.auth.password = "${OTLP_PASSWORD}"
protocol.headers.stream-name = "observe_nokiy_net"
