data_dir = "/var/lib/vector"

[api]
enabled = false

[sources.observe-nokiy-net]
type = "docker_logs"
include_containers = ["openobserve"]

[sinks.openobserve]
inputs = ["observe-nokiy-net"]
type = "http"
uri = "${OPENOBSERVE_URL}"
method = "post"
auth.strategy = "basic"
auth.user = "${OPENOBSERVE_USER}"
auth.password = "${OPENOBSERVE_PASSWORD}"
compression = "gzip"
encoding.codec = "json"
encoding.timestamp_format = "rfc3339"
healthcheck.enabled = false
